#!/usr/bin/env bash
rm ./*.class
javac ReturnObjectImplTest.java
java ReturnObjectImplTest
javac ArrayListTest.java
java ArrayListTest
javac LinkedListTest.java
java LinkedListTest
javac FunctionalArrayListTest.java
java FunctionalArrayListTest
javac FunctionalLinkedListTest.java
java FunctionalLinkedListTest
javac SampleableListImplTest.java
java SampleableListImplTest
javac StackImplTest.java
java StackImplTest
javac ImprovedStackImplTest.java
java ImprovedStackImplTest